[package]
name = "renderlib"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "30"
winit = { version = "0.30", features = ["x11", "rwh_06"], default-features = false}
pollster = "1"
bytemuck = { version = "1.16", features = ["derive"] }
anyhow = "1.0.104"
thiserror = "2.0.19"
env_logger = "0.11.11"
cgmath = "0.18"
